### ISSUE TITLE
필터 설정 모달을 수정한다

### ISSUE THREAD

**Issue by soyoung125** [soyoung125/fin-the-pen-web#1]
### ✨ Describe

필터 설정 모달 속 버튼의 위치 각 버튼의 동작을 수정합니다.

### ✅ Tasks

- [x] 필터 취소 버튼 제거
- [x] 필터 초기화 버튼 위치를 좌측 상단으로 변경
- [x] 필터 저장 버튼 추가
- [x] 저장 버튼 클릭 시 필터 저장 + 리포트에 필터 적용
- [x] 확인 버튼 클릭 시
  - [x] 필터 변경 사항이 있을 경우 알림 창 띄움
    - [x] '네' 선택 시 변경 사항 저장하지 않고 필터 닫기
    - [x] '아니오' 선택 시 알림 창 닫고 필터로 돌아감
  - [x] 변경 사항 없을 경우 필터 닫기

**Comment by gabrielyoon7** [comment]
혹시 권한 주셨나여

**Comment by soyoung125** [comment]
안드렸던거 같네요. 지금 설정할게요
