### ISSUE TITLE
ScheduleDrawer 자산 탭 디자인을 수정합니다.

### ISSUE THREAD

**Issue by soyoung125** [soyoung125/fin-the-pen-web#105]
### ✨ Describe

ScheduleDrawer 자산 탭 디자인을 수정합니다.

### ✅ Tasks

- [x] 금액 설정 validation 추가
- [x] 금액 설정 price_type 기호로 표현되게 수정
- [x] 일정 중요도 slider 적용
- [x] swiper 적용
