### ISSUE TITLE
scheduleDrawer 디자인을 수정합니다.

### ISSUE THREAD

**Issue by soyoung125** [soyoung125/fin-the-pen-web#122]
### ✨ Describe

scheduleDrawer 디자인을 수정합니다.

### ✅ Tasks

- [x] 드로어 스와이프 동작 범위 헤더로 제한
- [x] 스와이프 구현
- [x] 금액 설정 안되는 문제 해결
- [x] 테마 수정
- [x] divider 추가
- [x] 금액 설정 기호 위치 변경
