### ISSUE TITLE
dialog 기능을 개선한다

### ISSUE THREAD

**Issue by gabrielyoon7** [soyoung125/fin-the-pen-web#132]
### 🔨 Describe

기존의 dialog 사용이 좀 더 쉽도록 개선합니다.

### ✅ Tasks

- [x] approveText, rejectText 프롭 추가 (버튼 텍스트 표시용)
- [x] useContext를 custom hook으로 분리
    - [x] customAlert와 customConfirm을 미리 정의
        - [x] 허용할 버튼 종류를 미리 설정
        - [x] 확인/취소 버튼에 표시할 텍스트를 외부에서 줄 수 있음
    - [x] 타이틀, 디스크립션, 버튼텍스트만 줘도 기본 설정 가능
