### ISSUE TITLE
카테고리 선택 기능 디자인을 개선한다

### ISSUE THREAD

**Issue by gabrielyoon7** [soyoung125/fin-the-pen-web#137]
### 🔨 Describe

![image](https://github.com/soyoung125/fin-the-pen-web/assets/69189073/7532475f-3ba5-4e61-8ef5-cb0139c1849f)
새로운 디자인 및 구조로 변경합니다.

기존의 셀렉터는 제거합니다.

### ✅ Tasks

 - [ ] 셀렉터를 제거한다
 - [ ] 카테고리 선택 버튼 클릭 시 새로운 페이지로 이동한 것 같은 효과를 낸다
   - [ ] 카테고리 선택 시, 타입까지 자동으로 입력되어야 한다
   - [ ] 재사용성 및 확장성을 고려하여 설계한다
