### ISSUE TITLE
반복 옵션을 서버에 저장합니다.

### ISSUE THREAD

**Issue by soyoung125** [soyoung125/fin-the-pen-web#140]
### ✨ Describe

반복 옵션을 서버에 저장합니다.

### ✅ Tasks

- [x] schedule 데이터 구조 변경
- [x] repeat 구조 변경
  - [x] 매일 반복 데이터 저장
  - [x] 매주 반복 데이터 저장
  - [x] 매월 반복 데이터 저장
  - [x] 매년 반복 데이터 저장
- [x] period 구조 변경
  - [ ] 계속 반복 저장
  - [x] 반복 횟수 저장
  - [x] 반복 종료 기한 저장
