### ISSUE TITLE
useOverlay를 도입한다

### ISSUE THREAD

**Issue by gabrielyoon7** [soyoung125/fin-the-pen-web#148]
### 🔨 Describe

기존의 dialog 컴포넌트를 모두 제거하고 useOverlay로 대체합니다.

### ✅ Tasks

- [x] 기존의 dialog 컴포넌트를 제거합니다.
- [x] useOverlay로 대체합니다.
  - [x] 간략화 된 버전의 useOverlay를 사용합니다.
  - [x] 기존의 기능들은 커스텀 훅으로 정의하여 사용할 수 있도록 하고, 외부에서 컴포넌트를 주입하는 방식으로 개선합니다.
