### ISSUE TITLE
소비 리포트 관련 컴포넌트를 구현한다

### ISSUE THREAD

**Issue by gabrielyoon7** [soyoung125/fin-the-pen-web#149]
### ✨ Describe

재윤&민하님이 피그마에 만들어두신 소비 리포트 디자인 컴포넌트를 미리 구현해놓습니다.

<img width="351" alt="image" src="https://github.com/soyoung125/fin-the-pen-web/assets/69189073/177a519b-567c-4d94-9aae-72c757c42440">

![image](https://github.com/soyoung125/fin-the-pen-web/assets/69189073/a5e00e22-c278-40ab-8a27-da69938050f7)

### ✅ Tasks

- [ ] 색상을 순서대로 두도록 구현한다
- [ ] 각 %를 연동하여 색이 적절하게 채워질 수 있도록 한다
- [ ] 접기 모드와 펼치기 모드를 고려하여 구현한다
- [ ] 기존에 구현된 기능을 전면 개편합니다
