### ISSUE TITLE
시간 선택기를 최신 디자인에 맞춰 수정한다

### ISSUE THREAD

**Issue by gabrielyoon7** [soyoung125/fin-the-pen-web#151]
### 🔨 Describe

아직 구체적인 피그마 시안이 나온 것은 아니지만, 우선 사용성 검증을 위해 간단한 레이아웃 정도만 배치해서 올리겠습니다.

<img width="418" alt="image" src="https://github.com/soyoung125/fin-the-pen-web/assets/69189073/c780b30e-2243-4e8c-a65a-c0c82e864093">

디자인은 나중에 추가해주시면 그때 수정하겠습니다

### ✅ Tasks

- [ ] 기존 시간 선택기의 키패드를 제거한다
- [ ] 기존 시간 선택기와 다르게 오전/오후 버튼을 추가한다
- [ ] 잘못된 시간 입력에 대해서 에러 메시지를 추가한다
