### ISSUE TITLE
카테고리 버블 차트를 제작한다

### ISSUE THREAD

**Issue by gabrielyoon7** [soyoung125/fin-the-pen-web#170]
### 🔨 Describe

버블 차트 라이브러리를 사용하지 않고 동적으로 생성합니다

<img width="303" alt="image" src="https://github.com/soyoung125/fin-the-pen-web/assets/69189073/1a8e5ac8-ec0a-4171-a71a-0af360f0b2f0">

피그마 시안을 적용할 수 있도록 합니다.

### ✅ Tasks

- [ ] 반응형을 고려하여 배율을 정한다
- [ ] 원이 겹치지 않도록 한다
- [ ] 원 내부에는 제목과 비율을 줄 수 있도록 한다
- [ ] 원 색상을 정할 수 있도록 한다
- [ ] 원 크기를 비례하게 한다
- [ ] 랜덤으로 배치하되, 1개일 때에는 정 중앙에 배치되도록 한다
- [ ] 최대 5개가 생성될 수 있도록 한다
