### ISSUE TITLE
일부 기능을 개선한다

### ISSUE THREAD

**Issue by gabrielyoon7** [soyoung125/fin-the-pen-web#178]
### 🔨 Describe

재윤님이 테스트한 결과를 바탕으로 관련 버그를 모두 수정합니다.

### ✅ Tasks

- [x] BottomDrawer가 해상도에 제대로 맞지 않는 문제를 수정합니다.
- [x] BottomDrawer의 호출 부분을 useOverlay로 개선합니다.
- [x] MUI의 Dialog를 제거하고, 커스텀 합니다.
