### ISSUE TITLE
report 페이지 api 연동을 진행합니다.

### ISSUE THREAD

**Issue by soyoung125** [soyoung125/fin-the-pen-web#215]
### ✨ Describe

report 페이지 api 연동을 진행합니다.

### ✅ Tasks

- [x] 리포트 홈 화면 api 연동
- [ ] 리포트 카테고리별 상세 페이지 api 연동
- [x] 리포트 월별 상세 페이지 api 연동
