### ISSUE TITLE
디자인 문제를 해결합니다.

### ISSUE THREAD

**Issue by soyoung125** [soyoung125/fin-the-pen-web#221]
### 🔨 Describe

디자인 문제를 해결합니다.

디자인 팀의 qa 결과 확인된 결함을 해결합니다.

### ✅ Tasks

- [x] ScheduleDrawer 디자인 수정
- [x] TimeSelector 디자인 수정
- [x] DateSelector 디자인 수정
