### ISSUE TITLE
설정 페이지 디자인 수정합니다.

### ISSUE THREAD

**Issue by soyoung125** [soyoung125/fin-the-pen-web#23]
### ✨ Describe

설정 페이지 각 설정 아코디언 내의 설정 리스트 디자인을 수정합니다.

### ✅ Tasks

- [x] 아코디언 화살표 위치 우측으로 변경
- [x] 세부 설정 리스트 형식으로 변경
- [x] 세부 설정 아이콘 제거
- [x] switch 버튼 디자인 수정
- [x] 세부 설정 모두 추가
