### ISSUE TITLE
홈 화면 api 연결 방식을 수정합니다.

### ISSUE THREAD

**Issue by soyoung125** [soyoung125/fin-the-pen-web#237]
### 🔨 Describe

홈 화면 api 연결 방식을 수정합니다.

### ✅ Tasks

- [x] getMonthSchedules로 월별 탭과 일별 탭의 일정을 그립니다.
- [x] home/month api 호출 횟수를 조정합니다.
- [x] 홈화면 컴포넌트 디자인을 수정합니다.
