### ISSUE TITLE
qa/qc로 발견된 문제를 해결합니다.

### ISSUE THREAD

**Issue by soyoung125** [soyoung125/fin-the-pen-web#239]
### 🔨 Describe

qa/qc로 발견된 문제를 해결합니다.

### ✅ Tasks

- [x] 로그인
  - [x] 회원가입 성공에도 실패가 나오는 문제 해결
  - [x] 로그아웃 api 연동
- [x] scheduleDrawer
  - [x] 반복 기능 확성화시 반복 설정 화면 오픈
  - [x] 시간 입력 오류 해결
  - [x] 카테고리 별 입/출금 자동 변경
  - [x] 금액 입력 안되는 오류 해결
- [x] 폰트 변경
