### ISSUE TITLE
디자인 변경된 컴포넌트를 업데이트합니다.

### ISSUE THREAD

**Issue by soyoung125** [soyoung125/fin-the-pen-web#243]
### 🔨 Describe

디자인 변경된 컴포넌트를 업데이트합니다.

### ✅ Tasks

- [x] 오늘로 이동하는 TodayButton 수정
  - [x] 오늘, 이번주, 이번달 로 글자가 바뀌도록 수정
- [x] 리포트 페이지 사용 가능 금액 설명 수정
