### ISSUE TITLE
저축 목표 금액 설정 페이지를 수정합니다.

### ISSUE THREAD

**Issue by soyoung125** [soyoung125/fin-the-pen-web#249]
### 🔨 Describe

저축 목표 금액 설정 페이지를 수정합니다.

### ✅ Tasks

- [x]  설정 아이콘 변경
- [x]  설정 모달 헤더 수정
- [x]  개인 목표 설정 모달 폼 수정
- [x]  확인 알림 창 추가
