### ISSUE TITLE
카테고리별 자산 설정 api 연동을 진행합니다.

### ISSUE THREAD

**Issue by soyoung125** [soyoung125/fin-the-pen-web#265]
### ✨ Describe

카테고리별 자산 설정 api 연동을 진행합니다.

### ✅ Tasks

- [x] 카테고리별 자산 데이터 가져오기
- [x] 카테고리별 자산 설정하기
- [x] 카테고리별 자산 설정 컴포넌트 수정 모드 적용하기
