### ISSUE TITLE
카테고리별 자산 설정 페이지의 기능 구현을 마무리합니다.

### ISSUE THREAD

**Issue by soyoung125** [soyoung125/fin-the-pen-web#267]
### 🔨 Describe

카테고리별 자산 설정 페이지의 기능 구현을 마무리합니다.

### ✅ Tasks

- [x] mock api 구현
- [x] 설정 금액 비교하여 알림 띄우기
- [x] 초기화 api 연동
