### ISSUE TITLE
정기 입출금 금액 페이지 컴포넌트를 구현합니다.

### ISSUE THREAD

**Issue by soyoung125** [soyoung125/fin-the-pen-web#271]
### ✨ Describe

정기 입출금 금액 페이지 컴포넌트를 구현합니다.

### ✅ Tasks

- [x] 정기입출금 데이터 불러오기 api 연동
- [x] 정기 입금/출금 리스트 구현
- [x] 상세 리스트 구현
