### ISSUE TITLE
성능 최적화를 진행합니다.

### ISSUE THREAD

**Issue by soyoung125** [soyoung125/fin-the-pen-web#275]
### 🔨 Describe

성능 최적화를 진행합니다.
![image](https://github.com/soyoung125/fin-the-pen-web/assets/77377583/7dedc5e9-0506-4e06-8dd1-2a4c93175782)

### ✅ Tasks

- [x] 미사용 css 제거
  - [x] 미사용 font cdn 주소 제거
- [x] 번들 분할
  - [x] React.lazy() 사용
- [x] 빌드 옵션으로 rollup 적용해 번들 크기 줄이기
- [x] 접근성 향상시키기
