### ISSUE TITLE
QA/QC 버그 해결 및 ScheduleDrawer 변경된 디자인을 적용합니다.

### ISSUE THREAD

**Issue by soyoung125** [soyoung125/fin-the-pen-web#281]
### 🔨 Describe

QA/QC 버그 해결 및 ScheduleDrawer 변경된 디자인을 적용합니다.

### ✅ Tasks

- [x] ScheduleDrawer
  - [x] 일정 중요도 명칭을 결제 수단으로 수정
  - [x] 일정 등록/수정/삭제 후 ScheduleDrawer 비우기
  - [x] 변경된 디자인 적용
  - [x] 반복 내용 표시
- [x] main화면 금액 정보 반영
