### ISSUE TITLE
QA로 발견된 문제를 해결합니다.

### ISSUE THREAD

**Issue by soyoung125** [soyoung125/fin-the-pen-web#288]
### ✨ Describe

QA로 발견된 문제를 해결합니다.

### ✅ Tasks

- [x] 주별 탭 날짜 형식 수정
- [x] 카테고리별 자산 설정 자동 포커스 수정
- [x] 리포트 지출 목표 금액 페이지로 링크 연동
- [x] 피그마 토대로 자산 설정 페이지 디자인 수정
