### ISSUE TITLE
ScheduleDrawer 디자인을 수정합니다.

### ISSUE THREAD

**Issue by soyoung125** [soyoung125/fin-the-pen-web#294]
### 🔨 Describe

ScheduleDrawer 디자인을 수정합니다.

### ✅ Tasks

- [x] ScheduleDrawer 높이 조정
- [x] Puller 컴포넌트 적용
- [x] 템플릿 컴포넌트 위치 조정
