### ISSUE TITLE
정기 템플릿 관련 문제를 해결합니다.

### ISSUE THREAD

**Issue by soyoung125** [soyoung125/fin-the-pen-web#306]
### 🔨 Describe

정기템플릿 관련 문제를 해경합니다.

### ✅ Tasks

- [x] 동일한 정기 템플릿 존재 여부 확인 로직 수정
- [x] 자산 메뉴 replace 옵션 설정
- [x] SchrduleDrawer - 템플릿 리스트 - 관리 - 자산관리 넘어가는 과정에서 scheduleDrawer 내리기
- [x] scheduleDrawer 템플릿 없음 카드 디자인 수정
