### ISSUE TITLE
거래 내역 조회에서 조회 정렬 기준을 제거합니다.

### ISSUE THREAD

**Issue by soyoung125** [soyoung125/fin-the-pen-web#31]
### ✨ Describe

은행/계좌 거래 내역과 카드 내역 조회에서 조회 정렬 기준입력 칸을 제거합니다.

### ✅ Tasks

- [x] 조회 정렬 기준 입력 칸 제거
  - [x] 은행/계좌 거래 내역 조회 페이지
  - [x] 카드 거래 내역 조회 페이지
- [x] 조회 정렬 기준 값을 최신순으로 고정
