### ISSUE TITLE
정기 입출금 설정 모달을 수정합니다.

### ISSUE THREAD

**Issue by soyoung125** [soyoung125/fin-the-pen-web#33]
### ✨ Describe

정기 입출금 설정 모달의 별명 입력칸을 제거합니다.

### ✅ Tasks

- [x] 별명 입력 칸 제거
  - [x] 정기 입금 내역 설정 모달
  - [x] 정기 출금 내역 설정 모
