### ISSUE TITLE
Fix component design

### ISSUE THREAD

**Issue by soyoung125** [soyoung125/fin-the-pen-web#354]
### 🔨 Describe

Fix component design

### ✅ Tasks

- [x] 자산관리 페이지 스케쥴 현황 추천 소비 금액을 사용 가능 금액으로 바꾸기
- [x] 자동 로그아웃 시 -> 재로그인할 할 때 user 비우고 시작
- [x] 로그인 실패하면 시작화면으로 돌아가는 문제
- [x] 리포트 - 소비 금액이 있는데 예측 데이터가 없을 때 소비 예정 금액 설정 표시하기
- [x] 리포트 - 소비 카테고리 디테일 - 카테고리별 소비 예정 금액 설정하기 추가
- [x] 리포트 선택 일자 전역 변수로 변경하기
