### ISSUE TITLE
초기화 버튼 디자인을 수정합니다.

### ISSUE THREAD

**Issue by soyoung125** [soyoung125/fin-the-pen-web#45]
### ✨ Describe

초기화 버튼 디자인을 수정합니다.

### ✅ Tasks

- [x] 초기화 버튼 디자인 수정
  - [x] 필터 모달
  - [x] 저축 목표 설정 모달
  - [x] 개인 목표 설정 모달
  - [x] 카테고리별 자산설정
