### ISSUE TITLE
은행/카드 목록을 수정하고 디자인을 수정합니다.

### ISSUE THREAD

**Issue by soyoung125** [soyoung125/fin-the-pen-web#52]
### 🔨 Describe

은행/카드 목록을 수정하고 디자인을 수정합니다.

### ✅ Tasks

- [x] 은행/카드 목록 수정
- [x] 헤더 디자인 수정
- [x] 자산 조회 정렬 기준 디자인 수정
