### ISSUE TITLE
거래 내역 조회 페이지 디자인을 수정합니다.

### ISSUE THREAD

**Issue by soyoung125** [soyoung125/fin-the-pen-web#56]
### ✨ Describe

거래 내역 조회 페이지 디자인을 수정합니다.

### ✅ Tasks

- [x] 거래 내역 조회 title 카드 안으로 이동
- [x] 조회 기간, 정렬 기준 디자인 수정
- [x] 조회 버튼 문구 수정
- [x] 조회 버튼 위치 수정
