### ISSUE TITLE
로그인 페이지 디자인을 수정합니다.

### ISSUE THREAD

**Issue by soyoung125** [soyoung125/fin-the-pen-web#80]
### ✨ Describe

로그인 페이지 디자인을 수정합니다.

### ✅ Tasks

- [x] 로그인/회원가입 페이지의 핀더펜 로고 수정
- [x] 회원가입 페이지
  - [x] input간격 조정
  - [x] 비밀번호 확인 창 추가
  - [x] 하단 뒤로가기 버튼 제거
- [x] 로그인 페이지
  - [x] input간격 조정
  - [x] 비밀번호 보기 추가
