### ISSUE TITLE
Schedule 데이터 구조를 변경합니다.

### ISSUE THREAD

**Issue by soyoung125** [soyoung125/fin-the-pen-web#90]
### ✨ Describe

Schedule 데이터 구조를 변경합니다.

### ✅ Tasks

- [x] Schedule 데이터 구조 변경
  - [x]  schedule
    - [x] start_date, end_date 추가
    - [x] repeat/period/is_all_day 추가
  - [x] asset
    - [x] fix_amount 추가
- [x] 변경된 구조에 맞게 기능 구현
