### ISSUE TITLE
scheduleDrawer 디자인을 수정합니다.

### ISSUE THREAD

**Issue by soyoung125** [soyoung125/fin-the-pen-web#97]
### ✨ Describe

scheduleDrawer의 디장인을 수정합니다.

### ✅ Tasks

- [x] drawer 상단 디자인 수정
  - [x] 일정/자산 탭 우측으로 위치 변동
  - [x] 왼쪽 상단 초기화버튼 추가
- [x] 일정 추가 버튼 위 자동저장 문구 추가
- [x] input validation 추가
- [x] 반복 collape 추가
  - [x] 반복 주기 설정
  - [x] 반복 기간 설정
